CS Fixes
BoldGrid/w3-total-cache pull request #1007
Opened 2024-12-05 19:18 UTC by jacobd91

2025-03-04 20:21 UTC, cssjoe requested changes
See comments.

After this PR is merged, we'll focus on https://github.com/BoldGrid/w3-total-cache/pull/1028 and ensure that the updated Composer package for PHPCS is used in conjunction with our `phpcs.xml` file, and includes exclusion for the "lib" directory.

2025-03-04 20:21 UTC, cssjoe commented on Util_UsageStatistics.php
> +		} elseif ( 0 === $a[ $property2 ] ) {
The value may not be an `int` -- change to `} elseif ( empty( $a[ $property2 ] ) ) {`.

2025-03-04 20:21 UTC, cssjoe commented on Util_UsageStatistics.php
> +		if ( 0 === $divide_by ) {
`$divide_by` could be an `int` or `float` -- change to `if ( empty( $divide_by ) ) {`.

2025-03-04 20:21 UTC, cssjoe commented on Util_UsageStatistics.php
> +		} elseif ( 0 === $a[ $property2 ] ) {
The value may not be an `int` -- change to `} elseif ( empty( $a[ $property2 ] ) ) {`.

2025-03-07 16:38 UTC, jacobd91 commented on CacheFlush_Locally.php
> +	 *                      - 'only': (string) Flush specific cache type. Defaults to 'fragment'.
Updated

2025-03-07 16:42 UTC, jacobd91 commented on CacheFlush_Locally.php
> +	 *                      - 'only': (string) Flush specific cache type. Defaults to 'minify'.
Updated

2025-03-07 16:51 UTC, jacobd91 commented on Cache_File.php
> + * FIle: Cache_File.php
Fixed

2025-03-07 16:53 UTC, jacobd91 commented on Cache_Memcache.php
> +	 *                      - 'key_version_mode' (string): Mode for key versioning ('disabled' to disable it).
Updated

2025-03-07 16:54 UTC, jacobd91 commented on Cache_Nginx_Memcached.php
> + * FIle: Cache_Nginx_Memcached.php
Fixed

2025-03-07 16:54 UTC, jacobd91 commented on Cache_Memcached_Stats.php
> + * FIle: Cache_Memcached_Stats.php
Fixed

2025-03-07 16:55 UTC, jacobd91 commented on Cache_Memcached.php
> + * FIle: Cache_Memcached.php
Fixed

2025-03-07 16:56 UTC, jacobd91 commented on Cache_Memcache.php
> + * FIle: Cache_Memcache.php
Fixed

2025-03-10 17:11 UTC, cssjoe commented on Enterprise_Dbcache_WpdbInjection_Cluster.php
> +		} while ( $server_count < $this->min_tries );
This will cause an indefinite loop.  The `while` condition must check the `count` of `$servers` for every iteration.  You can change it to `while ( true )` and `break` if the condition is met.

2025-03-10 17:12 UTC, cssjoe commented on Extension_CloudFlare_Plugin.php
> +				while ( $count < 4 ) {
This will cause an indefinite loop.  The `while` condition must check the `count` of `$x` for every iteration.  You can change it to `while ( true )` and `break` if the condition is met.

2025-03-10 18:30 UTC, jacobd91 commented on Cache_Wincache.php
> + * FIle: Cache_Wincache.php
Fixed

2025-03-10 18:48 UTC, jacobd91 commented on CdnEngine_Azure_MI.php
> +				if ( isset( $p['Content-Length'] ) && $local_size === $p['Content-Length'] && isset( $p['Content-MD5'] ) && $content_md5 === $p['Content-MD5'] ) {
Casted both to int

2025-03-10 18:56 UTC, jacobd91 commented on CdnEngine_Base.php
> +	private $_config = array();
Updated

2025-03-10 18:56 UTC, jacobd91 commented on CdnEngine_Base.php
> +	private $_last_error = '';
Updated

2025-03-10 19:13 UTC, jacobd91 commented on CdnEngine_Mirror_StackPath.php
> +			if ( 0 === $zone_id || is_null( $zone_id ) ) {
Updated

2025-03-10 19:13 UTC, jacobd91 commented on CdnEngine_Mirror_StackPath.php
> +			if ( 0 === $zone_id || is_null( $zone_id ) ) {
Updated

2025-03-19 16:27 UTC, jacobd91 commented on Cdn_Highwinds_Api.php
> +			if ( isset( $response_json['code'] ) && '203' === $response_json['code'] ) {
Updated and cast to ints

2025-03-19 16:27 UTC, jacobd91 commented on Cdn_Highwinds_Api.php
> +		if ( '200' !== $result['response']['code'] && '201' !== $result['response']['code'] ) {
Updated and casted to int

2025-03-19 16:35 UTC, jacobd91 commented on Cdn_RackSpace_Api_Cdn.php
> +		) {
Updated and cast to int

2025-03-19 16:35 UTC, jacobd91 commented on Cdn_RackSpace_Api_Cdn.php
> +		) {
Updated and cast to int

2025-03-19 18:18 UTC, jacobd91 commented on Cdn_RackSpace_Api_CloudFiles.php
> +		) {
Updated and cast to int

2025-03-19 18:19 UTC, jacobd91 commented on Cdn_RackSpace_Api_CloudFilesCdn.php
> +		) {
Updated and cast to int

2025-03-19 18:19 UTC, jacobd91 commented on Cdn_RackSpace_Api_CloudFilesCdn.php
> +		) {
Updated and cast to int

2025-03-19 18:21 UTC, jacobd91 commented on Cdn_RackSpace_Api_Tokens.php
> +		if ( '200' !== $result['response']['code'] && '201' !== $result['response']['code'] ) {
Updated and cast to int

2025-03-19 18:29 UTC, jacobd91 commented on Cdn_StackPath_Popup.php
> +		if ( 0 === $v ) {
Changed

2025-03-19 18:38 UTC, jacobd91 commented on Cdnfsd_LimeLight_Api.php
> +		) {
Updated and cast to int

2025-03-19 18:40 UTC, jacobd91 commented on Cdnfsd_StackPath_Popup.php
> +		if ( 0 === $v ) {
Updated

2025-03-19 18:44 UTC, jacobd91 commented on ConfigCompiler.php
> +			'1' === $file_data['cdnfsd.enabled'] &&
Updated

2025-03-19 18:45 UTC, jacobd91 commented on ConfigCompiler.php
> +				'true' === $file_data['minify.enabled'] &&
Updated

2025-03-19 18:45 UTC, jacobd91 commented on ConfigState.php
> +		if ( 'false' === $v || 0 === $v ) {
Updated

2025-03-19 18:49 UTC, jacobd91 commented on Extension_CloudFlare_SettingsForUi.php
> +			if ( '' === $value ) {
Updated

2025-03-19 18:51 UTC, jacobd91 commented on Extension_NewRelic_AdminActions.php
> +		$application['alerts_enabled'] = 1 === $application['alerts_enabled'] ? 'true' : 'false';
Updated

2025-03-19 18:51 UTC, jacobd91 commented on Extension_NewRelic_AdminActions.php
> +		$application['rum_enabled']    = 1 === $application['rum_enabled'] ? 'true' : 'false';
Updated

2025-03-20 14:42 UTC, jacobd91 commented on Extension_NewRelic_Page.php
> -		if ( $view_metric = Util_Request::get_boolean( 'view_metric', false ) ) {
Fixed

2025-03-20 14:42 UTC, jacobd91 commented on Extension_NewRelic_Page.php
> +		include W3TC_DIR . '/Extension_NewRelic_Page_View_Apm.php';
Updated

2025-03-20 14:44 UTC, jacobd91 commented on Extension_Wpml_Plugin_Admin.php
> +			3 === $settings['language_negotiation_type']
Casted

2025-03-20 14:45 UTC, jacobd91 commented on Extensions_Page.php
> + * function extensions_sort_cmp_name( $a, $b ) {
Removed

2025-03-20 14:54 UTC, jacobd91 commented on Util_PageUrls.php
> +			if ( 'page' === get_option( 'show_on_front' ) && get_option( 'page_on_front' ) === $post_id ) {
Casted

2025-03-20 15:52 UTC, jacobd91 commented on Util_UsageStatistics.php
> +		} elseif ( 0 === $a[ $property2 ] ) {
Updated

2025-03-20 15:53 UTC, jacobd91 commented on Util_UsageStatistics.php
> +		if ( 0 === $divide_by ) {
Updated

2025-03-20 15:53 UTC, jacobd91 commented on Util_UsageStatistics.php
> +		} elseif ( 0 === $a[ $property2 ] ) {
Updated

2025-03-20 16:33 UTC, jacobd91 commented on Extension_CloudFlare_Plugin.php
> +				while ( $count < 4 ) {
After asking you about this you indicated that it would be okay as is. This should never result in an infinite loop

2025-03-20 16:53 UTC, jacobd91 commented on Enterprise_Dbcache_WpdbInjection_Cluster.php
> +		} while ( $server_count < $this->min_tries );
After speaking with you, you indicated that this should be okay but could still result in an infinite loop. To resolve this I added a counter and condition to the loop that will reattempt 3 times before ending if the number of servers is inadequate

2025-03-21 19:53 UTC, cssjoe approved these changes

2025-03-21 19:53 UTC, merged