Exit Survey
BoldGrid/w3-total-cache pull request #1018
Opened 2024-12-19 16:36 UTC by jacobd91

To test simply navigate to the plugins page and click on the deactivate link for W3 Total Cache. It should display a popup modal with an exit survey

2025-01-09 22:15 UTC, cssjoe requested changes
You missed one replacement and it caused a fatal error.
```
PHP Fatal error:  Uncaught Error: Call to undefined method W3TC\PageSpeed_Api::get_w3tc_api_url() in wp-content/plugins/w3-total-cache/inc/options/general.php:1287
```

See review comments.

2025-01-09 22:15 UTC, cssjoe commented on pub/js/exit-survey.js
> +			jQuery('#w3tc_exit_survey_uninstall_reason_other').hide().val(''); // Clear the "Other" input when not selected
Maybe don't clear the text box when changing options.  Just don't use the data if the reason is not "other".

2025-01-09 22:15 UTC, cssjoe commented on pub/js/lightbox.js
> +		this.container = jQuery('<div class="' + this.options.id + '"><div class="lightbox-close">' + this.options.close + '</div><div id="w3tc_lightbox_content" class="lightbox-content"></div><!-- Spinner
Change the inline style to a class "hidden".

2025-01-09 22:15 UTC, cssjoe commented on Root_Environment.php
> +	public static function delete_plugin_data() {
This deletes the WP Options for W3TC, but not directories such as "wp-content/cache/" (cache files) and "wp-content/w3tc-config/" (which contain "master.php" and possibly other files).

2025-01-10 19:04 UTC, jacobd91 commented on Generic_Plugin_Admin.php
> +				wp_create_nonce( 'w3tc' )
Updated to wrap the wp_create_nonce with an array

2025-01-10 19:05 UTC, jacobd91 commented on Generic_Plugin_Admin.php
> +			wp_enqueue_style( 'w3tc-exit-survey' );
Updated to just enqueue

2025-01-10 19:06 UTC, jacobd91 commented on Generic_Plugin_Survey.php
> + *
Added @since where missing

2025-01-10 19:07 UTC, jacobd91 commented on Generic_Plugin_Survey.php
> +		if ( ! isset( $_POST['_wpnonce'] ) || ! wp_verify_nonce( Util_Request::get_string( '_wpnonce' ), 'w3tc' ) ) {
isset removed

2025-01-10 19:09 UTC, jacobd91 commented on Util_Environment.php
> +		if ( ( defined( 'W3TC_PRO' ) && W3TC_PRO ) || ( defined( 'W3TC_ENTERPRISE' ) && W3TC_ENTERPRISE ) ) {
Updated to just return the logic result

2025-01-10 19:12 UTC, jacobd91 commented on Util_Environment.php
> +		return defined( 'W3TC_API2_URL' ) && W3TC_API2_URL ? esc_url( W3TC_API2_URL, 'https', '' ) : 'https://api2.w3-edge.com';
Enveloping array added

2025-01-10 19:12 UTC, jacobd91 commented on Util_Environment.php
> +	 *
@since added

2025-01-10 19:15 UTC, jacobd91 commented on Generic_Plugin_Survey.php
> +		if ( $api_response && isset( $api_response->status ) && 'Created' === $api_response->status ) {
Updated to

`if ( $api_response && 201 === wp_remote_retrieve_response_code( $api_response ) ) {`

2025-01-10 19:37 UTC, jacobd91 commented on inc/lightbox/exit_survey.php
> +				<input type="text" id="w3tc_exit_survey_uninstall_reason_other" name="other" placeholder="<?php esc_attr_e( 'Please specify...', 'w3-total-cache' ); ?>" style="width: 100%; margin-top: 5px;" />
Moved to the CSS file

2025-01-10 19:38 UTC, jacobd91 commented on inc/lightbox/exit_survey.php
> +				<input type="text" id="w3tc_exit_survey_uninstall_reason_other" name="other" placeholder="<?php esc_attr_e( 'Please specify...', 'w3-total-cache' ); ?>" style="width: 100%; margin-top: 5px;" />
Hidden class added

2025-01-10 19:46 UTC, jacobd91 commented on pub/js/exit-survey.js
> +/**
Header doc block added

2025-01-10 19:47 UTC, jacobd91 commented on pub/js/lightbox.js
> +		this.container = jQuery('<div class="' + this.options.id + '"><div class="lightbox-close">' + this.options.close + '</div><div id="w3tc_lightbox_content" class="lightbox-content"></div><!-- Spinner
Hidden class added and inline style removed

2025-01-10 19:54 UTC, jacobd91 commented on pub/js/exit-survey.js
> +			jQuery('#w3tc_exit_survey_uninstall_reason_other').hide().val(''); // Clear the "Other" input when not selected
Changed to not clear the value and updated the submit AJAX to only add it to the API data array if the reason selected is "other" and the reason textbox isn't blank

2025-01-13 16:55 UTC, cssjoe approved these changes

2025-01-13 16:56 UTC, merged