Redis cluster support
BoldGrid/w3-total-cache pull request #384
Opened 2021-06-15 13:52 UTC by dustinrue

This PR adds support for Redis running in a cluster mode. This is common when using AWS ElastiCache.

By default, the code will connect to Redis as it did previously. If W3TC_REDIS_CLUSTER is defined and set to true the connection will be made using RedisCluster instead of Redis. When used with AWS ElastiCache, only the Configuration Endpoint is needed.

2021-06-15 14:29 UTC, cssjoe requested changes
@dustinrue Thank you for submitting this contribution.  There are a few changes requested.  I also requested another one of our developers to review the request.  Please review my comments and make the changes.  Thank you.

2021-06-15 14:29 UTC, cssjoe commented on w3-total-cache.php
> +	// Set W3TC_REDIS_CLUSTER to true if using Redis in cluster mode
This new code block should go in the file `w3-total-cache-api.php`.

2021-06-15 14:29 UTC, cssjoe commented on Cache_Redis.php
> +				else {
Formatting is a little off.  Please change to:
`} else {`

2021-06-15 14:29 UTC, cssjoe commented on Cache_Redis.php
> +				if ( W3TC_REDIS_CLUSTER === true ) {
A better check would be:
`if ( defined( 'W3TC_REDIS_CLUSTER' ) && W3TC_REDIS_CLUSTER ) {`

2021-06-15 14:29 UTC, cssjoe commented on Cache_Redis.php
> +		if ( count( $this->_servers ) <= 1 || W3TC_REDIS_CLUSTER )
I better condition would be:
`if ( count( $this->_servers ) <= 1 || ( defined( 'W3TC_REDIS_CLUSTER' ) && W3TC_REDIS_CLUSTER ) ) {`

2021-06-15 14:29 UTC, cssjoe commented on Generic_AdminActions_Test.php
> +			if ( W3TC_REDIS_CLUSTER === true ) {
I better check would be:
`if ( defined( 'W3TC_REDIS_CLUSTER' ) && W3TC_REDIS_CLUSTER ) {`

2021-06-15 16:18 UTC, dustinrue commented
Thank you for the feedback. I have made the requested changes.

2021-08-25 14:02 UTC, maxicus commented
there are 3 redis connectivity classes available at the same time (Redis, RedisArray, RedisCluster). 
to keep similar with other parts of the code it should be controlled by string config parameter instead of hidden define, similar to `memcached.binary_protocol`

2021-11-03 14:09 UTC, dustinrue commented
I made some updates but I'm waiting on someone to help me test the changes

2023-01-20 16:38 UTC, cssjoe requested changes
See Max's previous comment:
>there are 3 redis connectivity classes available at the same time (Redis, RedisArray, RedisCluster).
to keep similar with other parts of the code it should be controlled by string config parameter instead of hidden define, similar to memcached.binary_protocol

Also, there are merge conflicts that have to be resolved.  There have been many updates since this pull request was opened.  Please resolve all merge conflicts and make updates based on Max's comment above.  We'll be happy to review this again after it has been updated.  Thank you.

2023-11-28 18:01 UTC, cssjoe commented
This pull request needs changes and have merge conflicts resolved.

2023-11-28 18:01 UTC, closed without merging