Added option for object cache to only flush post cache on post change #344
BoldGrid/w3-total-cache pull request #436
Opened 2021-09-28 17:28 UTC by jacobd91

2021-10-01 14:49 UTC, maxicus commented
Those hardcode of groups purging now will cause questions for sure. Also there are areas of conflict with objectcache.purge.all (which is not in UI whats bad) + there are cases when one just doesnt want to purge OC at all on posts changes relying on natural expiration when it works good enough.

I'm thinking what if add it in more advanced mode, and bound to events?
like 
Groups to flush 
- on posts change
- on comments activity
- on remaining events (like options change)

with possible value "<all>" in each list...

2021-12-29 16:53 UTC, maxicus requested changes
I see some extra complications = slowdowns added to dbcache, object cache, and removal of critical hooks like clean_post_cache (one called by wp to clean cache).
Effect is not straightforward. Can't assess if it a gain in average website env or slow down.

At least it's not solving my previous comment, but seems something else (not sure what). 
So... think we need to agree first what this PR is supposed to do enhance and in which cases.

2022-01-10 18:10 UTC, cssjoe requested changes
Max requested changes 12 days ago.  There are a lot of PHPCS WPCS violations.  Max mentioned if this update will increase performance.  We could profile the execution with XHPROF or similar.

2022-01-10 19:00 UTC, jacobd91 commented on ObjectCache_Plugin.php
> +			if( $this->_config->get_boolean( 'objectcache.purge.posts' ) ) {
Could you clarify on how this should be styled?

2023-11-24 17:05 UTC, jacobd91 commented
Abandoned

2023-11-24 17:05 UTC, closed without merging