Update to default QS exemptions
BoldGrid/w3-total-cache pull request #697
Opened 2023-06-12 19:43 UTC by jacobd91

In a previous update a hard-coded list was added to the accepted QS arguments that couldn't be modified via a setting. This PR migrates that list from a hard-coded implementation to merge it into the accepted QS setting.

This includes setting said list as the default for new users and merging it with existing values for users that set values.

Additionally an "Add Defaults" button has been added next to the accepted QS textarea under the Page Cache advanced settings that will merge said list with existing values.

2023-06-13 16:00 UTC, cssjoe requested changes
See the review comments.

2023-06-13 18:36 UTC, jacobd91 commented on Generic_Plugin_Admin.php
> +			$this->_config->set( 'pgcache.accept.qs', ksort( $pgcache_accept_qs ) );
Updated

2023-06-13 18:47 UTC, jacobd91 commented on PgCache_Page_View.js
> +			var $pgcacheQsExempts = jQuery('#pgcache_accept_qs').val().split("\n");
Removed the $

2023-06-13 18:48 UTC, jacobd91 commented on inc/options/pgcache.php
> +					<input type="button" class="button pgcache_qsexempts_default" value="Add Defaults" />
Updated to prefix with w3tc- and to replace _ with -

The rest of the file classes are not this format however.

2023-06-14 13:56 UTC, cssjoe requested changes

2023-06-14 13:56 UTC, cssjoe commented on Generic_AdminActions_Default.php
> +					$values = array_map( 'trim', array_filter( $config->get_array( $setting ) ) );
I don't see a callback function in array_filter().  Maybe you were trying to use it like this example:
https://www.php.net/manual/en/function.array-filter.php#114931
```
$value = $config->get_array( $setting );

if ( ! empty( $value ) ) {
    $array = array_filter( array_map( 'trim', $value ), 'strlen' );
```
That will trim all array values and then remove empty lines.

2023-06-14 16:28 UTC, cssjoe approved these changes

2023-06-14 16:29 UTC, merged