Reverted purchase/renew links back to popup modals with iframe cart
BoldGrid/w3-total-cache pull request #714
Opened 2023-07-12 18:36 UTC by jacobd91

This PR reverts all changes made to the purchase/renew buttons to restore the popup modals and iframe embeds of the cart. This allows for users to stay on-site and to automatically apply licenses on purchase

2023-07-12 20:25 UTC, cssjoe requested changes
Add escape and translate functions.

2023-07-12 23:56 UTC, jacobd91 commented on FeatureShowcase_Plugin_Admin_View.php
> +						echo '<button class="button w3tc-gopro-button button-buy-plugin" data-src="feature_showcase">Unlock Feature</button>';
Translation added and switch from echo to php break to print HTML

2023-07-12 23:57 UTC, jacobd91 commented on Licensing_Plugin_Admin.php
> +				'href'   => wp_nonce_url(
wp_nonce_url escapes the URL

2023-07-12 23:57 UTC, jacobd91 commented on Licensing_Plugin_Admin.php
> +				'href'   => wp_nonce_url( network_admin_url( 'admin.php?page=w3tc_dashboard&amp;w3tc_message_action=licensing_upgrade' ), 'w3tc' ),
wp_nonce_url escapes the URL

2023-07-13 19:09 UTC, cssjoe approved these changes

2023-07-13 19:10 UTC, merged