Cloudflare Extension API Fix
BoldGrid/w3-total-cache pull request #855
Opened 2024-04-01 16:34 UTC by jacobd91

Certain settings that use the Cloudflare API to set values rather than setting them in the W3TC config weren't updating through the API. This PR fixes that issue so that adjustments made to the settings properly set through the API

Example settings on the Cloudfare Settings page:

Minify CSS/JS/HTML

Before this PR, these wouldn't set through the API so reloading the page wouldn't reflect the change nor would it reflect on the Cloudflare settings page. If these were changed on the Cloudflare side, they would also change on W3TC but not vice-versa. With this PR, it now changes both ways

2024-04-29 17:12 UTC, cssjoe requested changes
There is one missing value ('120') for Browser Cache TTL.  Also, use the label 'Respect Existing Headers' for value '0'.  See [API - Change Browser Cache TTL setting](https://developers.cloudflare.com/api/operations/zone-settings-change-browser-cache-ttl-setting).  Maybe add a link to [Features by plan type](https://developers.cloudflare.com/cache/plans/) in the description.
I couldn't find the available values for the Edge Cache TTL.  The best documentation I found was [Cache Rules - Edge TTL](https://developers.cloudflare.com/cache/how-to/cache-rules/settings/#edge-ttl).

2024-04-30 14:45 UTC, jacobd91 commented on Extension_CloudFlare_Page_View.php
> +							'0'        => '',
Updated

2024-04-30 14:46 UTC, jacobd91 commented on Extension_CloudFlare_Page_View.php
>  							'60'       => '60',
Added

2024-04-30 14:57 UTC, cssjoe approved these changes

2024-04-30 15:43 UTC, merged